sudo: false
dist: trusty
language: go
addons:
  apt:
    packages:
    - librdkafka-dev
before_install:
- go get github.com/Masterminds/glide
- cd $GOPATH/src/github.com/Masterminds/glide && git checkout 84607742b10f492430762d038e954236bbaf23f7 && go install && cd -
install:
- glide install
- go get -u gopkg.in/alecthomas/gometalinter.v1
- go get -u github.com/golang/lint/golint
script:
- gometalinter.v1 ./... --config=linterconfig.json --vendor
