sudo: false
dist: trusty
language: go
addons:
  apt:
    sources:
    - ppa:masterminds/glide && sudo apt-get update
    packages:
    - librdkafka-dev
    - glide
install:
- glide install
- go get -u gopkg.in/alecthomas/gometalinter.v1
- go get -u github.com/golang/lint/golint
script:
- gometalinter.v1 ./... --config=linterconfig.json --vendor
