sudo: false
dist: trusty
language: go
addons:
  apt:
    packages:
    - librdkafka-dev
before_install:
- curl https://glide.sh/get | sh
install:
- glide install
- go get -u gopkg.in/alecthomas/gometalinter.v1
script:
- gometalinter.v1 ./... --config=linterconfig.json --vendor
