windowSize: 10
windowLag: 2
consumerTopic: metrics
producerTopic: metrics

kafka:
  bootstrap.servers: localhost:9092
  group.id: monasca-aggregation

aggregationSpecifications:
    - name: Aggregation0
      filteredMetricName: metric0
      aggregatedMetricName: aggregated-metric0
    - name: Aggregation1
      filteredMetricName: metric1
      aggregatedMetricName: aggregated-metric1
    - name: Aggregation2
      filteredMetricName: metric2
      aggregatedMetricName: aggregated-metric2