logging:
#  file: monasca-aggregation.log
  level: INFO

windowSize: 10
windowLag: 2
consumerTopic: metrics
producerTopic: metrics

kafka:
  bootstrap.servers: localhost:9092
  group.id: monasca-aggregation

prometheus:
  endpoint: localhost:8080