logging:
#  file: monasca-aggregation.log
  level: INFO

windowSize: 600
windowLag: 2
consumerTopic: metrics
producerTopic: metrics

kafka:
  bootstrap.servers: ms-monasca-kafka:9092
  group.id: monasca-aggregation

prometheus:
  endpoint: localhost:8080
