windowSize: 10
windowLag: 2

kafka:
  broker: localhost:9092
  group: monasca-aggregation
  consumerTopic: metrics
  producerTopic: metrics

aggregationSpecifications:
    - name: Aggregation0
      filteredMetricName: metric0
      aggregatedMetricName: aggregated-metric0
    - name: Aggregation1
      filteredMetricName: metric1
      aggregatedMetricName: aggregated-metric1
    - name: Aggregation2
      filteredMetricName: metric2
      aggregatedMetricName: aggregated-metric2